/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartView: typeof import('./components/ChartView.vue')['default']
    ChatPanel: typeof import('./components/ChatPanel.vue')['default']
    DataGrid: typeof import('./components/DataGrid.vue')['default']
    DatasetDrawer: typeof import('./components/DatasetDrawer.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MessageComposer: typeof import('./components/MessageComposer.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    ObservabilityDrawer: typeof import('./components/ObservabilityDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolResultView: typeof import('./components/ToolResultView.vue')['default']
    TraceStep: typeof import('./components/TraceStep.vue')['default']
    TraceTimeline: typeof import('./components/TraceTimeline.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
